- README.md
- applications/prod/namespace.yaml
- applications/staging/namespace.yaml
- applications/test/namespace.yaml
* Se añaden los entornos que argocd hará pull
* Se estructura y se añaden los namespaces
> Feat: add environments and namespaces

- applications/core/cert-manager/cloudflare-api-token.yaml
* Cambiar el api token por la api key de cloudflare para poder ver todas los records de la zona
> Fix: change cloudflare api token to check everything

- applications/core/argo-cd/argocd.yaml
Close #14 
* First iteration was by hand
* Now ArgoCD is pulling itself and we can modify its values
> Feat: auto pull itself in gitops way

- applications/core/argo-cd/argocd.yaml
* Remove ingress approach
* Use LoadBalancer as type in service
> Feat: add service type as loadbalancer

- applications/core/argo-cd/argocd.yaml
* Allow org-admin group make changes
> Fix: add permissions to admin group

- environments/test/official-website.yaml
resolves #13 
* Add application to deploy test official-website
> Feat: deploy test website to test ns

- applications/core/cluster-autoscaler/bindings.yaml
- applications/core/cluster-autoscaler/clusterrole.yaml
- applications/core/cluster-autoscaler/deployment.yaml
- applications/core/cluster-autoscaler/role.yaml
- applications/core/cluster-autoscaler/sa.yaml
solves #46 
* Add cluster-autoscaler manifests
* Configure number of workers
> Feat: add clusterautoscaler yaml manifests

- applications/core/prometheus-stack/prom-grafana.yaml
solves #45 
* Deploy Prometheus and Grafana
> Feat: add prometheus stack by default

- applications/core/monitoring/prometheus-grafana.yaml
- Add the prometheus and grafana stack to core applications in order to deploy it with argocd
> feat(core): add monitoring apps

- applications/core/monitoring/prometheus-grafana.yaml
- Set recursive argo app to scrape all the resources
> fix(monitoring): set recursive source

- applications/core/metrics-server/metrics-server.yaml
* Add metrics-server app for scaling with HPA
* Enable prometheus metrics to scrape them
> Feat: add metrics server for scaling and scrape metrics

- applications/monitoring/prometheus/kube-prometheus.yaml
> Fix: raise memory to 1Gi and test its performance

- applications/monitoring/grafana/dashboards/exporter-full-dashboard.yaml
- applications/monitoring/grafana/dashboards/k3s-dashboard.yaml
* Add k3s dashboard to see kubernetes resources
> Feat: add k3s dashboard

- applications/monitoring/OpenSearch/opensearch-dashboard.yaml
- applications/monitoring/OpenSearch/opensearch.yaml
Test opensearch in our cluster in single node
> Feat: add opensearch to the cluster

- applications/monitoring/grafana/dashboards/loki-logs-dashboard.yaml
- loki dashboard now has needed env variables to work
> Fix: Loki Dashboard

- applications/security/kyverno/kyverno.yaml
> Fix: disable cleanup jobs

- applications/core/argo-cd/sso-secret.encrypted.yaml
- applications/core/traefik/ingressroute.yaml
- applications/monitoring/grafana/dashboards/k3s-dashboard.yaml
- applications/monitoring/grafana/dashboards/trivy-vulnerabilities-dashboard.yaml
- applications/permission-manager/ingress.yaml
- applications/permission-manager/kustomization.yaml
- applications/permission-manager/namespace.yaml
- applications/permission-manager/secret.encrypted.yaml
- applications/security/kyverno/policies/mutate/default-labels.yaml
- applications/security/kyverno/policies/validation/latest-tag.yaml
- applications/security/kyverno/policies/validation/limits-requests.yaml
- applications/security/kyverno/policies/validation/no-default-ns.yaml
- applications/security/trivy/namespace.yaml
- applications/security/trivy/trivy-operator.yaml
It involves setting up the Trivy Operator to facilitate the scanning of container images for security vulnerabilities and the Grafana Dashboard to monitorize those.
- Fixes #70
> Feat: Deploy Trivy Operator to scan vulnerabilities

- .github/labeler.yml
- .github/workflows/pr-labeler.yaml
Automate the adding labels to the PRs
> Feat: add auto labeler to avoid think in labels

- .github/labeler.yml
- applications/core/cluster-autoscaler/deployment.yaml
It is proposed to rollback to 1 node minimum in the node pool because we raised the instance type
> Fix: rollback to 1 node minimum in autoscaling pool

- applications/core/argo-cd/argocd.yaml
After install ArgoCD by hand, bump the current version is required
> Feat: bump argo to the last version

- applications/core/argocd/argocd.yaml
Add ArgoCD again to manage all resources
> Feat: add argo to pull himself

- README.md
* Use the same private and public key in all clusters deployed
* Document the process
> Doc: add how-to use the same private key to the cluster

- applications/core/minio/minio.yaml
- crds/core/minio/minio-creds.encrypted.yaml
* Deploy minio to the cluster
* Use credentials secret to llogin
close #98 
Access to webui [here](https://minio.cloudnativerioja.com)
> Feat: add minio chart and its secret

- applications/core/cert-manager/cert-manager.yaml
- applications/core/cluster-autoscaler/deployment.yaml
- applications/core/external-dns/external-dns.yaml
- applications/core/traefik/traefik.yaml
Upgrade the follow charts:
* Cert-manager
* External-dns
* Cluster-autoscaler
* Traefik
> Feat: upgrade chart versoins

- applications/core/minio/minio.yaml
* Expose minio api to allocate tfstates
* Persistence the objects
> Feat: add persistence and open minio api

- applications/core/cert-manager/cert-manager.yaml
- applications/core/external-dns/external-dns.yaml
* Add limits and requests to cert-manager and external-dns charts
> Feat: add resource limits and requests to cert-manager and external-dns

- applications/core/traefik/traefik.yaml
* Fix identation to deploy the new changes
> Fix: identation error

- applications/core/traefik/traefik.yaml
- crds/core/traefik/dash-ingress.yaml
- crds/core/traefik/dash-service.yaml
- crds/core/traefik/middleware.yaml
* No tls secret so no https, the problem was the tls identation
* Move files to crd/traefik to isolate them
> Fix: move code to files in crds

- crds/core/traefik/dash-service.yaml
* Fix annotation to bind service to the pod
> Fix: use the right annotation to select it

- .github/workflows/pr-labeler.yaml
* Add pull requests stats to get information about CR and PR
> Feat: add pull request stats

- applications/core/kyverno/kyverno.yaml
* Deploy Kyverno application to set policies
* Deploy its grafana dashboard
> Feat: deploy kyverno and its grafana dashboard

- applications/monitoring/prometheus/kube-prometheus.yaml
* To allow get kyverno metrics and see in grafana dashboard, prometheus needs to scrape those metrics from kyverno metrics endpoint
> Feat: add scrape configuration to kyverno metrics

- applications/monitoring/prometheus/kube-prometheus.yaml
> Chore: typo in scrape metrics

- applications/monitoring/prometheus/kube-prometheus.yaml
* Reach the right kyverno metrics service name
* JobList under internal identation
> Fix: add the right kyverno service name and add internal config

- crds/core/kyverno_policies/generate-cloudflare-secret.yaml
* Generation policy to deploy the same secret in all namespaces but default
> Feat: add kyverno policy to generate cloudflare secret

- applications/core/cert-manager/cert-manager.yaml
- applications/core/cluster-autoscaler/deployment.yaml
- applications/core/kyverno/kyverno.yaml
- applications/core/traefik/traefik.yaml
- applications/monitoring/grafana/grafana-operator.yaml
- applications/monitoring/loki/loki.yaml
- applications/monitoring/prometheus/kube-prometheus.yaml
- crds/core/kyverno_policies/generate-cloudflare-secret.yaml
* Bump applications versions to the latest
* Fix kyverno cloudflare policy
> Feat: bump versions and fix kyverno policy

- applications/core/cluster-autoscaler/deployment.yaml
- applications/core/cluster-autoscaler/service.yaml
- applications/monitoring/prometheus/kube-prometheus.yaml
* Export cluster-autoscaler metrics
* Scrape them with prometheus
> Feat: scrape cluster-autoscaler metrics

- crds/core/argo-rollouts/pod-info/canary-rollout-podinfo.yaml
- crds/core/argo-rollouts/rollout-bluegreen-demo/bluegreen-rollout.yaml
- crds/core/argo-rollouts/rollouts-canary-demo/canary-rollout.yaml
> Feat: remove replicas

- crds/core/monitoring/grafana/dashboards/autoscaler-dashboard.yaml
* Add cluster-autoscaler dashboard to see the behaviour of the cluster
> Feat: add autoscaler dashboard to grafana

- applications/core/kyverno/kyverno.yaml
* Due to this [issue](https://github.com/kyverno/kyverno/pull/9119) is required to bump the version
> Feat: bump kyverno chart version

- applications/monitoring/grafana/grafana-operator.yaml
- applications/monitoring/prometheus/kube-prometheus.yaml
* Move Grafana and Prometheus to a dedicated node
> Feat: move monitoring workloads to a dedicated node

- applications/core/argocd/argocd.yaml
- applications/core/cluster-autoscaler/deployment.yaml
* Isolate ArgoCD and clusterautoscaler
> Feat: add tolerations to argo and autoscaler

- applications/core/argocd/argocd.yaml
- applications/core/kyverno/kyverno.yaml
- crds/core/kyverno_policies/default-namespace.yaml
- crds/core/kyverno_policies/disallow-latest-tag.yaml
- crds/core/kyverno_policies/ingress-annotations.yaml
* Remove kyverno
* Change argocd ingress
> Feat: remove kyverno and change argo ingress

- crds/core/monitoring/grafana/dashboards/cilium-agent-dashboard.yaml
- crds/core/monitoring/grafana/dashboards/cilium-operator-dashboard.yaml
- crds/core/monitoring/grafana/dashboards/hubble-dashboard.yaml
- crds/core/monitoring/grafana/dashboards/kyverno-dashboard.yaml
* Cilium agent, operator and hubble dashboards are added and metrics scraped
> Feat: add cilium dashboards to grafana
